# Generated by Django 3.0.5 on 2020-04-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='contact',
            field=models.IntegerField(default=True),
        ),
    ]
